// Code generated by "stringer -type=IdProvider"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Google-1]
}

const _IdProvider_name = "Google"

var _IdProvider_index = [...]uint8{0, 6}

func (i IdProvider) String() string {
	i -= 1
	if i < 0 || i >= IdProvider(len(_IdProvider_index)-1) {
		return "IdProvider(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _IdProvider_name[_IdProvider_index[i]:_IdProvider_index[i+1]]
}
